### ISSUE TITLE
paper-menu-button doesn't work in Firefox

### ISSUE THREAD

**Issue by zoechi** [dart-lang/paper-elements#80]
I built this example https://github.com/bwu-dart/bwu_fontawesome_iconset_svg/blob/master/example/example01.html#L59
This works fine in Dartium and Chrome but in Firefox clicking on the button doesn't open the drop-down menu. 
Pressing the <kbd>Space</kbd> button when the button has focus does open the menu though.
The code is very similar to the example at https://www.polymer-project.org/docs/elements/paper-elements.html#paper-menu-button and the demo linked from this page works fine in Firefox therefore I assume it is an issue with the Dart port of the element(s).

**Comment by jakemac53** [comment]
Looks like the polymer port of the example is also broken

**Comment by jakemac53** [comment]
looks like on-tap is broken in FF

**Comment by zoechi** [comment]
Would be interesting which Polymer or Polymer-gestures version the demo uses which works fine in Firefox. Probably an older version.

**Comment by jakemac53** [comment]
newer version in 0.5.2 works, we just decided to roll polymer 0.5.2 to get the fix (but are not rolling other related packages, at least yer)

**Comment by jakemac53** [comment]
should be fixed as of polymer 0.15.5
