### ISSUE TITLE
cherry-pick #109 from paper-input

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/paper-elements#81]
We should bring in the changes from this commit:

https://github.com/Polymer/paper-input/commit/67770602863f0802b862102c2f684ea7f91d5f9c

**Comment by sigmundch** [comment]
This might be more complex than I initially thought - that commit depends on other changes that we haven't rolled yet. I'll see if cherry-picking a couple commits could work, but it might be necessary to do a more agressive roll of the elements...

**Comment by jakemac53** [comment]
We might need to roll the elements anyways, specifically for `core-resizable` which was designed to resolve some annoying issues with `core-list-dart`.

**Comment by sigmundch** [comment]
yeah, I think so too.
