### ISSUE TITLE
PaperButton inheritance not seen by darteditor

### ISSUE THREAD

**Issue by pstjvn** [dart-lang/paper-elements#84]
For some reason PaperButton does not seem to understand that is extends PaperButtonBase and thus DartEditor cannot reason about its properties. Navigating to the source code of PaperButton and using F3 (open definition) on PaperButtonBase does not work. 

I have tried re-analizing the project but it does not help. I am not sure if it is a bug of a glitch in Dart editor, so excuse me if this is not the right place to submit this.

**Comment by jakemac53** [comment]
This is working for me, did you try restarting the editor?

**Comment by pstjvn** [comment]
Yes, restarting fixed it. That was strange... DartEditor does this and not for first time... 
Thank you

**Comment by jakemac53** [comment]
Ya it does tend to just get in a bad state sometimes :(
