### ISSUE TITLE
Refresh upstream elements?

### ISSUE THREAD

**Issue by burnnat** [dart-lang/paper-elements#85]
In attempting to do some custom styling on a `paper-toggle-button`, I discovered that the element structure has changed quite drastically between the most recent JS version (0.5.5) and the version bundled with the paper_elements package (0.5.1).

Rather than having to backport all my styling changes, I'd much rather get the updated toggle button instead. Are there any plans in the works to update the bundled JS elements to a more recent version?

**Comment by jakemac53** [comment]
This is definitely on the radar, but nobody is working on it yet. We have fallen a bit behind on this but after I wrap up my current work I should be able to dedicate some time to it.

**Comment by jakemac53** [comment]
done, released as 0.7.0
