### ISSUE TITLE
0.6.2 paper_tabs failed to inline HTML import error

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/paper-elements#87]
Trying to import paper_tabs.dart

`[Warning from ImportInliner on app|web/index.html]:
line 85, column 1 of lib/src/paper-tabs/paper-tabs.html: Failed to inline HTML import: Could not find asset paper_elements|lib/src/core-resizable/core-resizable.html.
null
<link rel="import" href="../core-resizable/core-resizable.html">`

**Comment by zoechi** [comment]
have you tried `pub cache repair` and `pub get`?

**Comment by terrywarwar** [comment]
Just tried it and now there's an unrelated error.  Build error:
Transform polymer (PolymerBootstrapTransformer) on app|web/index.html threw error: Bad state: No element

Will get back to you once I figure out once I resolve this.

**Comment by zoechi** [comment]
The next step would be to delete the paper-elements directory from `~/.pub-cache/hosted/pub.dartlang.org/` or the equivalent directory on non-Linux OS. If this doesn't help purge the `~/.pub-cache/hosted/`directory and run `pub get` again.

**Comment by jakemac53** [comment]
Looks like I can repro this, taking a look

**Comment by jakemac53** [comment]
https://codereview.chromium.org/1002463002/ out to fix it, should be merged/published soon

**Comment by jakemac53** [comment]
published fix as paper_elements 0.6.2+1
