### ISSUE TITLE
paper-slider change event gives wrong value

### ISSUE THREAD

**Issue by vsheyanov** [dart-lang/paper-elements#90]
Sample app:

https://gist.github.com/vsheyanov/9df9e1904f8b21465e65

If you change Slider value by dragging thumb, console output would be:
```
change: 
12
core-change: 
12
```

But if you just click to required position, output would be:
```
change: 
12 (wrong)
core-change: 
41 (correct)
```
next click
```
41 (wrong)
core-change: 
19 (correct)
```

Looks like there is a delay in one click for 'change' event.

I've check and it works fine regular Polymer
http://jsbin.com/yiroduqude/1/edit?html,console,output

**Comment by jakemac53** [comment]
The new version (currently in the repo but not published yet) fixes this.
